export const birthCountryOptions = [
  "Afghanistan",
  "Afrique du Sud",
  "Albanie",
  "Algérie",
  "Allemagne",
  "Andorre",
  "Angola",
  "Arabie saoudite",
  "Argentine",
  "Arménie",
  "Australie",
  "Autriche",
  "Belgique",
  "Bénin",
  "Brésil",
  "Bulgarie",
  "Burkina Faso",
  "Burundi",
  "Cameroun",
  "Canada",
  "Cap-Vert",
  "Centrafrique",
  "Chili",
  "Chine",
  "Colombie",
  "Comores",
  "Congo",
  "Côte d'Ivoire",
  "Croatie",
  "Danemark",
  "Djibouti",
  "Égypte",
  "Émirats arabes unis",
  "Espagne",
  "États-Unis",
  "Éthiopie",
  "Finlande",
  "France",
  "Gabon",
  "Gambie",
  "Ghana",
  "Grèce",
  "Guinée",
  "Guinée-Bissau",
  "Guinée équatoriale",
  "Haïti",
  "Inde",
  "Irlande",
  "Italie",
  "Japon",
  "Kenya",
  "Liban",
  "Luxembourg",
  "Madagascar",
  "Mali",
  "Maroc",
  "Maurice",
  "Mauritanie",
  "Mexique",
  "Niger",
  "Nigeria",
  "Norvège",
  "Pays-Bas",
  "Pologne",
  "Portugal",
  "République démocratique du Congo",
  "Roumanie",
  "Royaume-Uni",
  "Rwanda",
  "Sénégal",
  "Suisse",
  "Tchad",
  "Togo",
  "Tunisie",
  "Turquie",
  "Ukraine",
] as const;

export type BirthCountry = (typeof birthCountryOptions)[number];

export function isBirthCountry(value: string): value is BirthCountry {
  return birthCountryOptions.includes(value as BirthCountry);
}

